Updated to have error codes in the services
PickNikRobotics/ros_testing_templates pull request #39
Opened 2023-09-20 00:13 UTC by bgill92

## Description

The service messages now have error codes.

## Testing

In the docker container run 

```
colcon build
colcon test
```
Make sure there are no test failures

2023-09-20 23:12 UTC, griswaldbrooks commented
looks like you forgot to add the new messages

2023-09-23 19:33 UTC, griswaldbrooks requested changes
First pass

2023-09-23 19:33 UTC, griswaldbrooks commented on functional_programming_tests/include/pathing/pathing.hpp
> +  EMPTY_OCCUPANCY_MAP = 1,
is there anyway you can include the message files and do, something like
```
EMPTY_OCCUPANCY_MAP = GetPathCodes::msg::EMPTY_OCCUPANCY_MAP
```
idk what the actual constant is named or if this is even possible.
I've just noticed in past projects that having these two sources of truth can cause issues

2023-09-23 19:33 UTC, griswaldbrooks commented on functional_programming_tests/src/pathing.cpp
> +  response.code.code = 0;
I would add a success message to the enum/message file and use that so we don't use numbers and stick with semantics

2023-09-23 19:33 UTC, griswaldbrooks commented on functional_programming_tests/src/pathing_manager.cpp
> +    std::cerr << "In path callback, map size is : " << this->map_.get_data().size() << "\n";
still need this? or should you use `mw_->log_error` here so the side effects are captured

2023-09-23 19:33 UTC, griswaldbrooks commented on functional_programming_tests/src/pathing_manager.cpp
> +        };
I think you can just return `void`
```suggestion
        auto const set_map = [this](Map<unsigned char> const map)
        -> tl::expected<void, utilities::parsing_set_map_error> {
          this->map_ = map;
          return;
        };
```

2023-09-23 19:33 UTC, griswaldbrooks commented on functional_programming_tests/src/pathing_manager.cpp
> +        auto const return_successful_response = []([[maybe_unused]] auto const success)
```suggestion
        auto const return_successful_response = []([[maybe_unused]] auto const) 
```

2023-09-23 19:33 UTC, griswaldbrooks commented on functional_programming_tests/src/pathing_manager.cpp
> +          response.code.code = 0;
same comment about using the named variable from the error code message or enum

2023-09-23 19:33 UTC, griswaldbrooks commented on functional_programming_tests/src/pathing_manager.cpp
> +          mw_->log_error(std::string{utilities::parsing_set_map_error_description.at(error)});
does
```suggestion
          mw_->log_error(utilities::parsing_set_map_error_description.at(error));
```
work?

2023-09-23 19:33 UTC, griswaldbrooks commented on functional_programming_tests/src/pathing_manager.cpp
> +      mw_->log_error(std::string{pathing::generate_path::error_description.at(error)});
```suggestion
      mw_->log_error(pathing::generate_path::error_description.at(error));
```
?

2023-09-23 19:33 UTC, griswaldbrooks commented on example_srvs/srv/GetPath.srv
> +example_srvs/GetPathCodes code
maybe this should be
```suggestion
example_srvs/GetPathCodes result
```
so latter the setter is
```
result.code = ...
```

2023-10-25 14:06 UTC, bgill92 commented on functional_programming_tests/src/pathing_manager.cpp
> +    std::cerr << "In path callback, map size is : " << this->map_.get_data().size() << "\n";
I think that was an artifact of me debugging, removing.

2023-10-25 14:07 UTC, bgill92 commented on functional_programming_tests/src/pathing_manager.cpp
> +        };
Nope, compiling fails

2023-10-25 14:09 UTC, bgill92 commented on functional_programming_tests/src/pathing_manager.cpp
> +          mw_->log_error(std::string{utilities::parsing_set_map_error_description.at(error)});
Yee

2023-10-25 14:36 UTC, griswaldbrooks submitted a review, later dismissed

2023-10-25 14:48 UTC, griswaldbrooks approved these changes

2023-10-25 14:55 UTC, merged